# Generated by Django 4.0.6 on 2022-11-18 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alocacao',
            name='cliente',
        ),
        migrations.CreateModel(
            name='venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='api.cliente')),
                ('concessionaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concessionarias', to='api.concessionaria')),
            ],
        ),
    ]
